# Generated by Django 5.1.3 on 2025-03-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stranik_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
