# Generated by Django 5.1.3 on 2024-12-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stranik_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
