# Generated by Django 5.1.3 on 2025-03-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stranik_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': 'Аренда', 'verbose_name_plural': 'Аренда'},
        ),
        migrations.RemoveField(
            model_name='rent',
            name='date',
        ),
        migrations.AddField(
            model_name='rent',
            name='text',
            field=models.TextField(default='Default text', verbose_name='Дополнительная информация по локации:'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название локации'),
        ),
    ]
