# Generated by Django 5.1.3 on 2025-03-19 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stranik_app', '0002_alter_rent_options_remove_rent_date_rent_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Время публикации'),
        ),
    ]
