# Generated by Django 5.1.3 on 2025-02-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stranik_app', '0002_alter_rent_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'ordering': ['-date'], 'verbose_name': 'Аренда', 'verbose_name_plural': 'Аренда'},
        ),
        migrations.AlterField(
            model_name='rent',
            name='cost_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена (числовое значение)'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название локации'),
        ),
    ]
