# Generated by Django 5.1.3 on 2025-03-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stranik_app', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
